---
language: node_js
node_js:
  - "7.10.1"

sudo: false

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=wheely-projects-1
  - EMBER_TRY_SCENARIO=wheely-projects-2

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=wheely-projects-2

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember try:one $EMBER_TRY_SCENARIO
